/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        slug: 'getting-started',
      },
      items: ['getting-started/installation'],
      collapsed: false,
    },
    'safelist',
    'proxy'
  ],
  apiSidebar: [
    {
      type: 'doc',
      label: 'Main',
      id: 'api/README',
    },
    {
      type: 'category',
      label: 'Classes',
      items: [{
        type: 'autogenerated',
        dirName: 'api/classes',
      }]
    },
    {
      type: 'category',
      label: 'Enums',
      items: [{
        type: 'autogenerated',
        dirName: 'api/enums',
      }]
    },
    {
      type: 'category',
      label: 'Interfaces',
      items: [{
        type: 'autogenerated',
        dirName: 'api/interfaces',
      }]
    },
    {
      type: 'category',
      label: 'Modules',
      items: [{
        type: 'autogenerated',
        dirName: 'api/modules',
      }]
    },
  ],
};

export default sidebars;
